Fixing MSVC build
frno7/libpes pull request #6
Opened 2022-02-16 14:39 UTC by Talhada

Those changes fix the msvc build. Based on issue #4  the following changes were made:
   1. I initialized all structs with `={0};` instead of `={}` which gives a compilation error.
   1. Linking with math library is not done on windows systems that use MSVC (-lm flag also results on error)
   1. Added .vs folder to .gitignore for Visual Studio users. 

Let me know what you think.

2022-02-16 16:00 UTC, frno7 commented
Thanks, @Talhada! Would you be able to rebase your commit series onto HEAD? The first five commits have already been merged, so we shouldn’t merge them again. Commit 52dcc0f28fe32255a507d8854e43fce812a8c1fa fixes the preceding commit in the same series, so that ought to be squashed.

2022-02-16 16:08 UTC, frno7 commented on src/pec-encoder.c
> +	struct pec_thumbnail thumbnail = {0};
Please indent this as `{ 0 }` (with spaces). And the first element of the structure is actually an array, so there might be compiler warnings with this. Could you use designated initialisers with proper types?

2022-02-16 16:09 UTC, frno7 requested changes
There are three changes in this commit, and so I think we should split them into three separate commits.

2022-02-21 09:55 UTC, closed without merging

2022-02-21 14:15 UTC, Talhada commented
Ups, I did something wrong and  accidentally closed the issue. I was trying to make the rebase on git. Sorry, im pretty new to GitHub and the workflow still confuses me a bit

2022-02-21 14:29 UTC, frno7 commented
No worries, keep on practicing. :-)